### ISSUE TITLE
Make NHANCE based clocks compatible with scikit-learn. Easy for ML experiments.

### ISSUE THREAD

**Issue by MartinPerez** [bio-learn/biolearn#19]
As is, clocks are run like functions on full datasets and is not possible to apply them with point or matrix predictions. They force themselves into the passed dataframe which is a bad practice. Let's employ the scikit-learn conventions to handle models and datasets.

**Comment by sarudak** [comment]
Do you have a link or description to the scikit learn standards you want to follow? I believe we had a conversation about this at some point and you sent me a link but I can't find it. If this is just about mutating inputs to clocks I agree with you but it sounds like you're suggesting more changes to the interface
