### ISSUE TITLE
'DNAmTL' model predicts negative telomere length?

### ISSUE THREAD

**Issue by RPMohanty** [bio-learn/biolearn#52]
Hi,

While predicting telomere length, for example, 'GSE36054', gallery.get("DNAmTL").predict() outputs all negative values:
```
data_source = DataLibrary().get("GSE36054")
data=data_source.load()
res = gallery.get("DNAmTL").predict(data)
print(res)
```
The above code outputs all negative values:
```
	Predicted
GSM879994	-9.46633965073063
GSM879995	-7.274470275919961
GSM879996	-7.889198651644749
GSM879997	-7.475846701552349
```

I tested the above on multiple data sets but the same results.

Q. What am I missing here? Is this the right way? Is it not telomere length in kb (should be between 6-10 kb?)?

I looked into the code and found that in the transformation function, (the lambda function lambda sum) **sum - 7.924780053**  subtracts a constant from the calculated sum. If the sum of the coefficients and the methylation data is smaller than 7.924780053, the result will be negative.
```
    "DNAmTL": {
        "year": 2019,
        "species": "Human",
        "tissue": "Blood, Adipose",
        "source": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6738410/",
        "output": "Telomere Length",
        "model": {
            "type": "LinearMethylationModel",
            "file": "DNAmTL.csv",
            "transform": lambda sum: sum - 7.924780053,
        },
```
I wonder if **7.924780053** was supposed to be added instead of subtracted?
```sum - 7.924780053```  -->  ```sum + 7.924780053```

So, to test the above, I added **7.924780053 * 2** to all the outputs as:
```
pos_value = 7.924780053 * 2
res = gallery.get("DNAmTL").predict(data2)
res_adjusted = [x+pos_value for x in res['Predicted']]
res['adj_Predicted'] = res_adjusted
res
```
Which, outputs:
```
	Predicted	adj_Predicted
GSM879994	-9.46633965073063	6.38322045526937
GSM879995	-7.274470275919961	8.575089830080039
GSM879996	-7.889198651644749	7.960361454355251
GSM879997	-7.475846701552349	8.37371340444765
```
Column **adj_Predicted** contains the length assuming ```sum + 7.924780053``` and this fits with the expected telomere length in kb.

Some explanation will really be helpful and appreciated,

Thanks.

**Comment by sarudak** [comment]
Apologies for my late reply and I appreciate this thorough write up. I talked to Mahdi about this and he said that this is the expected results. I intended to do some investigation in the paper to see if I could find some context around the interpretation of the result number but got distracted with challenge setup tasks. All that is to say I don't really have an answer for you currently but I would look into the paper linked to the model (https://bio-learn.github.io/clocks.html) and see if it provides any insights.
