### ISSUE TITLE
Add IPython to pyproject.toml dependencies.

### ISSUE THREAD

**Issue by jeremymchacon** [bio-learn/biolearn#63]
Very minor issue, but when I start a fresh conda env with python=3.10, and then only install biolearn into it, the test case:

```

from biolearn.data_library import DataLibrary

```

fails because it depends on IPython. Adding it to pyproject.toml should work. Thanks for the cool project!

Edit: As I work through the clock examples, I also find that sklearn is an unnamed dependency.

**Comment by sarudak** [comment]
Thanks for noticing this. I actually ran into this myself recently. I need to do a little thinking on if I want to make IPython a core dependency for the library. 

As far as the example dependencies you should be covered if you install biolearn with the dev dependencies enabled, scikit-learn is included as a dev dependency.

**Comment by sarudak** [comment]
I just discovered that this dependency is just for a single unused import. It will be removed for the next release.
